import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Simple Pomodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={`overflow-hidden bg-slate-100 antialiased`}>
        {children}
      </body>
    </html>
  );
}
